name: C/C++ CI

on: push

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install newer version of cmake
      uses: lukka/get-cmake@v3.18.0
    - name: Build using cmake
      run: mkdir build; cd build; cmake ..; cmake --build .
    - name: Copy build results
      run: mkdir build/Analyzers/linux; cp build/Analyzers/* build/Analyzers/linux
    - name: Store build result as artifact
      uses: actions/upload-artifact@v2
      with:
        name: SENTanalyzer
        path: build/Analyzers

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install newer version of cmake
      uses: lukka/get-cmake@v3.18.0
    - name: Build using cmake
      run: mkdir build; cd build; cmake ..; cmake --build .
    - name: Copy build results
      run: mkdir build/Analyzers/macOS; cp build/Analyzers/* build/Analyzers/macOS
    - name: Store build result as artifact
      uses: actions/upload-artifact@v2
      with:
        name: SENTanalyzer
        path: build/Analyzers

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install newer version of cmake
      uses: lukka/get-cmake@v3.18.0
    - name: Build using cmake
      run: mkdir build; cd build; cmake ..; cmake --build . --config Release
    - name: Copy build results
      run: mkdir build/Analyzers/windows; cp build/Analyzers/Release/* build/Analyzers/windows
    - name: Store build result as artifact
      uses: actions/upload-artifact@v2
      with:
        name: SENTanalyzer
        path: build/Analyzers
