name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get-cmake
      # You may pin to the exact commit or the version.
      # uses: lukka/get-cmake@0c94bc3245aa84e9f8344d6d735886e6cae06894
      uses: lukka/get-cmake@v3.18.0
    - name: build using cmake
      run: mkdir build; cd build; cmake ..; cmake --build .
    - name: Save dist folder contents as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SENTanalyzer
        path: build/
